### ISSUE TITLE
Getting error message when choosing Exit prompt after Tow a vehicle choice is selected but unable to complete. Error posted in description below.

### ISSUE THREAD

**Issue by DevynJohnson** [DevynJohnson/funWithVehicles#11]
file:///C:/Users/devyn/Bootcamp/funWithVehicles/node_modules/@inquirer/core/dist/esm/lib/create-prompt.js:55
            reject(new ExitPromptError(`User force closed the prompt with ${code} ${signal}`));
                   ^

ExitPromptError: User force closed the prompt with 0 null
    at file:///C:/Users/devyn/Bootcamp/funWithVehicles/node_modules/@inquirer/core/dist/esm/lib/create-prompt.js:55:20
    at Emitter.emit (file:///C:/Users/devyn/Bootcamp/funWithVehicles/node_modules/signal-exit/dist/mjs/index.js:67:19)
    at #processEmit (file:///C:/Users/devyn/Bootcamp/funWithVehicles/node_modules/signal-exit/dist/mjs/index.js:236:27)
    at #process.emit (file:///C:/Users/devyn/Bootcamp/funWithVehicles/node_modules/signal-exit/dist/mjs/index.js:187:37)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by DevynJohnson** [comment]
Issue resolved. No longer required to force close application due to issue with overlapping inquirer prompts.
